import crypto from "node:crypto";
import { chmodSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve, sep } from "node:path";
import process from "node:process";
import bcrypt from "bcryptjs";
import pg from "pg";

const { Pool } = pg;
const DEFAULT_BOOTSTRAP_SECRETS_FILE = "/tmp/noosphere-bootstrap-secrets/secrets.json";
const ALLOWED_BOOTSTRAP_SECRETS_PARENT_ROOTS = [
  "/tmp/noosphere-bootstrap-secrets",
  "/app/uploads/bootstrap-secrets",
];
const TOPICS = JSON.parse(
  readFileSync(new URL("./bootstrap-topics.json", import.meta.url), "utf8"),
);

function requireEnv(name) {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function hashApiKey(key) {
  return crypto.createHash("sha256").update(key).digest("hex");
}

function generateApiKey() {
  return `noo_${crypto.randomBytes(32).toString("base64url")}`;
}

function id() {
  return crypto.randomUUID();
}

export function collectGeneratedSecrets({
  adminPassword,
  adminPasswordAutoGenerated,
  adminPasswordApplied,
  apiKey,
  apiKeyAutoGenerated,
}) {
  const credentials = {};
  if (adminPasswordAutoGenerated && adminPasswordApplied) {
    credentials.adminPassword = adminPassword;
  }
  if (apiKeyAutoGenerated) {
    credentials.apiKey = apiKey;
  }
  return credentials;
}

function readExistingGeneratedCredentials(secretsFile) {
  try {
    const parsed = JSON.parse(readFileSync(secretsFile, "utf8"));
    if (parsed && typeof parsed === "object" && parsed.credentials && typeof parsed.credentials === "object") {
      return parsed.credentials;
    }
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  return {};
}

function isWithinDirectory(path, root) {
  return path === root || path.startsWith(`${root}${sep}`);
}

function ensurePrivateSecretsParent(parentDir) {
  const resolvedParentDir = resolve(parentDir);
  if (!ALLOWED_BOOTSTRAP_SECRETS_PARENT_ROOTS.some((root) => isWithinDirectory(resolvedParentDir, root))) {
    throw new Error(
      "NOOSPHERE_BOOTSTRAP_SECRETS_FILE must point inside a dedicated private directory, " +
        "for example /tmp/noosphere-bootstrap-secrets/secrets.json or " +
        "/app/uploads/bootstrap-secrets/secrets.json.",
    );
  }

  mkdirSync(resolvedParentDir, { recursive: true, mode: 0o700 });
  chmodSync(resolvedParentDir, 0o700);
}

export function writeGeneratedSecretsFile(credentials) {
  if (Object.keys(credentials).length === 0) return null;

  const secretsFile = process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE || DEFAULT_BOOTSTRAP_SECRETS_FILE;
  ensurePrivateSecretsParent(dirname(secretsFile));
  const mergedCredentials = {
    ...readExistingGeneratedCredentials(secretsFile),
    ...credentials,
  };
  const tmpFile = `${secretsFile}.${process.pid}.${crypto.randomBytes(8).toString("hex")}.tmp`;
  try {
    writeFileSync(
      tmpFile,
      `${JSON.stringify({
        createdAt: new Date().toISOString(),
        credentials: mergedCredentials,
      }, null, 2)}\n`,
      { flag: "wx", mode: 0o600 },
    );
    chmodSync(tmpFile, 0o600);
    renameSync(tmpFile, secretsFile);
  } catch (error) {
    rmSync(tmpFile, { force: true });
    throw error;
  }
  return secretsFile;
}

function formatBootstrapError(error) {
  const details = [];
  if (error instanceof Error && error.name) details.push(`name=${error.name}`);
  if (error && typeof error === "object" && "code" in error && typeof error.code === "string") {
    details.push(`code=${error.code}`);
  }
  const suffix = details.length > 0 ? ` (${details.join(", ")})` : "";
  return `[bootstrap] Failed to initialize Noosphere${suffix}. Verify database and bootstrap configuration.`;
}

async function upsertTopic(client, topic, parentId = null) {
  const updateResult = await client.query(
    `UPDATE "Topic"
     SET name = $2,
         description = $3,
         "parentId" = $4,
         "updatedAt" = NOW()
     WHERE slug = $1
     RETURNING id`,
    [topic.slug, topic.name, topic.description ?? null, parentId],
  );

  if (updateResult.rows[0]?.id) return updateResult.rows[0].id;

  const result = await client.query(
    `INSERT INTO "Topic" (id, name, slug, description, "parentId", "createdAt", "updatedAt")
     VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
     ON CONFLICT (slug) DO UPDATE SET
       name = EXCLUDED.name,
       description = EXCLUDED.description,
       "parentId" = EXCLUDED."parentId",
       "updatedAt" = NOW()
     RETURNING id`,
    [id(), topic.name, topic.slug, topic.description ?? null, parentId],
  );
  return result.rows[0].id;
}

async function main() {
  const databaseUrl = requireEnv("DATABASE_URL");
  const adminEmail = process.env.NOOSPHERE_ADMIN_EMAIL || "admin@noosphere.local";
  const adminPassword = process.env.NOOSPHERE_ADMIN_PASSWORD || crypto.randomBytes(24).toString("base64url");
  const adminName = process.env.NOOSPHERE_ADMIN_NAME || "Noosphere Admin";
  const rawApiKey = process.env.NOOSPHERE_BOOTSTRAP_API_KEY || generateApiKey();
  const apiKeyName = process.env.NOOSPHERE_API_KEY_NAME || "OpenClaw Noosphere Memory";
  const permissions = process.env.NOOSPHERE_API_KEY_PERMISSIONS || "ADMIN";

  if (!["READ", "WRITE", "ADMIN"].includes(permissions)) {
    throw new Error("NOOSPHERE_API_KEY_PERMISSIONS must be READ, WRITE, or ADMIN");
  }

  const pool = new Pool({ connectionString: databaseUrl });
  const client = await pool.connect();
  let transactionOpen = false;
  try {
    await client.query("BEGIN");
    transactionOpen = true;

    const passwordHash = await bcrypt.hash(adminPassword, 12);
    const forceAdmin = process.env.NOOSPHERE_FORCE_ADMIN === "true";
    const resetAdminPassword = process.env.NOOSPHERE_ADMIN_PASSWORD_RESET === "true";
    const adminResult = await client.query(
      `INSERT INTO "User" (id, email, name, "passwordHash", role, "createdAt", "updatedAt")
       VALUES ($1, $2, $3, $4, 'ADMIN', NOW(), NOW())
       ON CONFLICT (email) DO UPDATE SET
         name = EXCLUDED.name,
         "passwordHash" = CASE
           WHEN $5::boolean THEN EXCLUDED."passwordHash"
           ELSE "User"."passwordHash"
         END,
         role = CASE
           WHEN $6::boolean THEN 'ADMIN'::"Role"
           ELSE "User".role
         END,
         "updatedAt" = NOW()
       RETURNING (xmax = 0) AS inserted`,
      [id(), adminEmail, adminName, passwordHash, resetAdminPassword, forceAdmin],
    );
    // Postgres marks freshly inserted rows with xmax=0; conflicted updates do not.
    const adminCreated = Boolean(adminResult.rows[0]?.inserted);
    const adminPasswordApplied = adminCreated || resetAdminPassword;

    for (const topic of TOPICS) {
      const parentId = await upsertTopic(client, topic, null);
      for (const child of topic.children ?? []) {
        await upsertTopic(client, child, parentId);
      }
    }

    const keyHash = hashApiKey(rawApiKey);
    const keyPrefix = rawApiKey.slice(0, 8);
    await client.query(
      `INSERT INTO "ApiKey" (id, name, "keyHash", "keyPrefix", permissions, "createdAt")
       VALUES ($1, $2, $3, $4, $5::"Permissions", NOW())
       ON CONFLICT ("keyHash") DO UPDATE SET
         name = EXCLUDED.name,
         permissions = EXCLUDED.permissions,
         "revokedAt" = NULL`,
      [id(), apiKeyName, keyHash, keyPrefix, permissions],
    );

    const adminPasswordAutoGenerated = !process.env.NOOSPHERE_ADMIN_PASSWORD;
    const apiKeyAutoGenerated = !process.env.NOOSPHERE_BOOTSTRAP_API_KEY;

    await client.query("COMMIT");
    transactionOpen = false;

    const generatedSecretsFile = writeGeneratedSecretsFile(collectGeneratedSecrets({
      adminPassword,
      adminPasswordAutoGenerated,
      adminPasswordApplied,
      apiKey: rawApiKey,
      apiKeyAutoGenerated,
    }));

    console.log(JSON.stringify({
      ok: true,
      adminEmail,
      adminPasswordAutoGenerated,
      apiKeyAutoGenerated,
      generatedSecretsFile,
      permissions,
    }));

    if (generatedSecretsFile) {
      console.error(
        `[bootstrap] Auto-generated credentials written to ${generatedSecretsFile} with mode 0600.`,
      );
    }
  } catch (error) {
    if (transactionOpen) await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error(formatBootstrapError(error));
    process.exit(1);
  });
}
