import crypto from "node:crypto";
import {
  chmodSync,
  closeSync,
  fsyncSync,
  linkSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  realpathSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve, sep } from "node:path";
import process from "node:process";
import bcrypt from "bcryptjs";
import pg from "pg";

const { Pool } = pg;
const DEFAULT_BOOTSTRAP_SECRETS_FILE = "/tmp/noosphere-bootstrap-secrets/secrets.json";
const ALLOWED_BOOTSTRAP_SECRETS_PARENT_ROOTS = [
  "/tmp/noosphere-bootstrap-secrets",
  "/app/uploads/bootstrap-secrets",
];
const TOPICS = JSON.parse(
  readFileSync(new URL("./bootstrap-topics.json", import.meta.url), "utf8"),
);

class SafeBootstrapError extends Error {}

function requireEnv(name) {
  const value = process.env[name];
  if (!value) throw new SafeBootstrapError(`${name} is required`);
  return value;
}

function hashApiKey(key) {
  return crypto.createHash("sha256").update(key).digest("hex");
}

function generateApiKey() {
  return `noo_${crypto.randomBytes(32).toString("base64url")}`;
}

function id() {
  return crypto.randomUUID();
}

export function collectGeneratedSecrets({
  adminPassword,
  adminPasswordAutoGenerated,
  adminPasswordApplied,
  apiKey,
  apiKeyAutoGenerated,
}) {
  const credentials = {};
  if (adminPasswordAutoGenerated && adminPasswordApplied) {
    credentials.adminPassword = adminPassword;
  }
  if (apiKeyAutoGenerated) {
    credentials.apiKey = apiKey;
  }
  return credentials;
}

function readExistingGeneratedCredentials(secretsFile) {
  try {
    const parsed = JSON.parse(readFileSync(secretsFile, "utf8"));
    if (parsed && typeof parsed === "object" && parsed.credentials && typeof parsed.credentials === "object") {
      return parsed.credentials;
    }
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  return {};
}

function isWithinDirectory(path, root) {
  return path === root || path.startsWith(`${root}${sep}`);
}

function ensureDirectoryTreeWithoutSymlinks(directory) {
  const resolvedDirectory = resolve(directory);
  let current = sep;
  for (const segment of resolvedDirectory.split(sep).filter(Boolean)) {
    current = join(current, segment);
    let stat;
    try {
      stat = lstatSync(current);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
      mkdirSync(current, { mode: 0o700 });
      // Persist both the new directory entry and its initial metadata before a
      // later database commit can depend on files stored below it.
      fsyncPath(dirname(current));
      fsyncPath(current);
      stat = lstatSync(current);
    }
    if (stat.isSymbolicLink() || !stat.isDirectory()) {
      throw new SafeBootstrapError(
        `Bootstrap secrets directory components must be real directories: ${current}`,
      );
    }
  }
  return realpathSync(resolvedDirectory);
}

function ensurePrivateSecretsParent(parentDir) {
  const resolvedParentDir = resolve(parentDir);
  const allowedRoot = ALLOWED_BOOTSTRAP_SECRETS_PARENT_ROOTS.find((root) =>
    isWithinDirectory(resolvedParentDir, root));
  if (!allowedRoot) {
    throw new SafeBootstrapError(
      "NOOSPHERE_BOOTSTRAP_SECRETS_FILE must point inside a dedicated private directory, " +
        "for example /tmp/noosphere-bootstrap-secrets/secrets.json or " +
        "/app/uploads/bootstrap-secrets/secrets.json.",
    );
  }

  const realParentDir = ensureDirectoryTreeWithoutSymlinks(resolvedParentDir);
  const realAllowedRoot = realpathSync(resolve(allowedRoot));
  if (!isWithinDirectory(realParentDir, realAllowedRoot)) {
    throw new SafeBootstrapError(
      "NOOSPHERE_BOOTSTRAP_SECRETS_FILE cannot traverse symbolic links outside its private directory.",
    );
  }
  chmodSync(realParentDir, 0o700);
  return realParentDir;
}

function fsyncPath(path) {
  const fd = openSync(path, "r");
  try {
    fsyncSync(fd);
  } finally {
    closeSync(fd);
  }
}

function rejectUnsafeExistingSecretsFile(secretsFile) {
  try {
    const stat = lstatSync(secretsFile);
    if (stat.isSymbolicLink() || !stat.isFile()) {
      throw new SafeBootstrapError(
        `Existing bootstrap secrets path must be a regular file: ${secretsFile}`,
      );
    }
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
}

export function stageGeneratedSecretsFile(credentials) {
  if (Object.keys(credentials).length === 0) return null;

  const secretsFile = process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE || DEFAULT_BOOTSTRAP_SECRETS_FILE;
  const parentDir = ensurePrivateSecretsParent(dirname(secretsFile));
  rejectUnsafeExistingSecretsFile(secretsFile);
  const pendingFile = `${secretsFile}.pending`;
  const mergedCredentials = {
    ...readExistingGeneratedCredentials(secretsFile),
    ...credentials,
  };
  const tmpFile = `${pendingFile}.${process.pid}.${crypto.randomBytes(8).toString("hex")}.tmp`;
  let pendingClaimed = false;
  try {
    writeFileSync(
      tmpFile,
      `${JSON.stringify({
        createdAt: new Date().toISOString(),
        credentials: mergedCredentials,
      }, null, 2)}\n`,
      { flag: "wx", mode: 0o600 },
    );
    chmodSync(tmpFile, 0o600);
    fsyncPath(tmpFile);
    // Hard-link creation is an atomic no-replace claim: concurrent bootstrap
    // processes cannot replace an existing recovery artifact.
    linkSync(tmpFile, pendingFile);
    pendingClaimed = true;
    rmSync(tmpFile);
    fsyncPath(parentDir);
  } catch (error) {
    rmSync(tmpFile, { force: true });
    if (error?.code === "EEXIST") {
      throw new SafeBootstrapError(
        `Generated credentials are already staged at ${pendingFile}. ` +
          "Recover or remove that file before retrying bootstrap.",
        { cause: error },
      );
    }
    if (pendingClaimed) {
      throw new SafeBootstrapError(
        `Generated credentials remain staged at ${pendingFile}, but durability ` +
          "could not be confirmed. Verify that file before retrying bootstrap.",
        { cause: error },
      );
    }
    throw error;
  }
  return { pendingFile, secretsFile };
}

export function publishGeneratedSecretsFile(stagedSecrets) {
  if (!stagedSecrets) return null;
  const parentDir = dirname(stagedSecrets.secretsFile);
  const publishFile = `${stagedSecrets.secretsFile}.${process.pid}.` +
    `${crypto.randomBytes(8).toString("hex")}.publish`;
  try {
    // Keep the pending hard link until the final rename is durable. A crash or
    // rename failure therefore leaves at least one path to the committed bytes.
    linkSync(stagedSecrets.pendingFile, publishFile);
    renameSync(publishFile, stagedSecrets.secretsFile);
    fsyncPath(parentDir);
    // The final name is durable at this point. Pending removal is cleanup only;
    // if a crash resurrects that entry, the next bootstrap blocks safely.
    try {
      rmSync(stagedSecrets.pendingFile);
    } catch (cleanupError) {
      const cleanupCode = cleanupError && typeof cleanupError === "object" &&
        "code" in cleanupError && typeof cleanupError.code === "string"
        ? ` (code=${cleanupError.code})`
        : "";
      console.error(
        `[bootstrap] Credentials were published, but stale recovery cleanup failed${cleanupCode}. ` +
          `Remove ${stagedSecrets.pendingFile} before the next bootstrap run.`,
      );
    }
  } catch (error) {
    rmSync(publishFile, { force: true });
    if (error?.code === "ENOENT") {
      throw new SafeBootstrapError(
        `Database bootstrap committed, but the staged credentials file is missing or unavailable: ` +
          stagedSecrets.pendingFile,
        { cause: error },
      );
    }
    throw new SafeBootstrapError(
      `Database bootstrap committed, but generated credentials remain staged at ` +
        `${stagedSecrets.pendingFile}. Move that file to ${stagedSecrets.secretsFile} ` +
        "before starting Noosphere.",
      { cause: error },
    );
  }
  return stagedSecrets.secretsFile;
}

export function writeGeneratedSecretsFile(credentials) {
  return publishGeneratedSecretsFile(stageGeneratedSecretsFile(credentials));
}

function formatBootstrapError(error) {
  const details = [];
  if (error instanceof Error && error.name) details.push(`name=${error.name}`);
  if (error && typeof error === "object" && "code" in error && typeof error.code === "string") {
    details.push(`code=${error.code}`);
  }
  const suffix = details.length > 0 ? ` (${details.join(", ")})` : "";
  const safeMessage = error instanceof SafeBootstrapError ? `: ${error.message}` : "";
  return `[bootstrap] Failed to initialize Noosphere${suffix}${safeMessage}. Verify database and bootstrap configuration.`;
}

async function upsertTopic(client, topic, parentId = null) {
  const updateResult = await client.query(
    `UPDATE "Topic"
     SET name = $2,
         description = $3,
         "parentId" = $4,
         "updatedAt" = NOW()
     WHERE slug = $1
     RETURNING id`,
    [topic.slug, topic.name, topic.description ?? null, parentId],
  );

  if (updateResult.rows[0]?.id) return updateResult.rows[0].id;

  const result = await client.query(
    `INSERT INTO "Topic" (id, name, slug, description, "parentId", "createdAt", "updatedAt")
     VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
     ON CONFLICT (slug) DO UPDATE SET
       name = EXCLUDED.name,
       description = EXCLUDED.description,
       "parentId" = EXCLUDED."parentId",
       "updatedAt" = NOW()
     RETURNING id`,
    [id(), topic.name, topic.slug, topic.description ?? null, parentId],
  );
  return result.rows[0].id;
}

async function main() {
  const databaseUrl = requireEnv("DATABASE_URL");
  const adminEmail = process.env.NOOSPHERE_ADMIN_EMAIL || "admin@noosphere.local";
  const adminPassword = process.env.NOOSPHERE_ADMIN_PASSWORD || crypto.randomBytes(24).toString("base64url");
  const adminName = process.env.NOOSPHERE_ADMIN_NAME || "Noosphere Admin";
  const rawApiKey = process.env.NOOSPHERE_BOOTSTRAP_API_KEY || generateApiKey();
  const apiKeyName = process.env.NOOSPHERE_API_KEY_NAME || "OpenClaw Noosphere Memory";
  const permissions = process.env.NOOSPHERE_API_KEY_PERMISSIONS || "ADMIN";

  if (!["READ", "WRITE", "ADMIN"].includes(permissions)) {
    throw new SafeBootstrapError("NOOSPHERE_API_KEY_PERMISSIONS must be READ, WRITE, or ADMIN");
  }

  const pool = new Pool({ connectionString: databaseUrl });
  const client = await pool.connect();
  let transactionOpen = false;
  let stagedGeneratedSecrets = null;
  try {
    await client.query("BEGIN");
    transactionOpen = true;

    const passwordHash = await bcrypt.hash(adminPassword, 12);
    const forceAdmin = process.env.NOOSPHERE_FORCE_ADMIN === "true";
    const resetAdminPassword = process.env.NOOSPHERE_ADMIN_PASSWORD_RESET === "true";
    const adminResult = await client.query(
      `INSERT INTO "User" (id, email, name, "passwordHash", role, "createdAt", "updatedAt")
       VALUES ($1, $2, $3, $4, 'ADMIN', NOW(), NOW())
       ON CONFLICT (email) DO UPDATE SET
         name = EXCLUDED.name,
         "passwordHash" = CASE
           WHEN $5::boolean THEN EXCLUDED."passwordHash"
           ELSE "User"."passwordHash"
         END,
         role = CASE
           WHEN $6::boolean THEN 'ADMIN'::"Role"
           ELSE "User".role
         END,
         "updatedAt" = NOW()
       RETURNING (xmax = 0) AS inserted`,
      [id(), adminEmail, adminName, passwordHash, resetAdminPassword, forceAdmin],
    );
    // Postgres marks freshly inserted rows with xmax=0; conflicted updates do not.
    const adminCreated = Boolean(adminResult.rows[0]?.inserted);
    const adminPasswordApplied = adminCreated || resetAdminPassword;

    for (const topic of TOPICS) {
      const parentId = await upsertTopic(client, topic, null);
      for (const child of topic.children ?? []) {
        await upsertTopic(client, child, parentId);
      }
    }

    const keyHash = hashApiKey(rawApiKey);
    const keyPrefix = rawApiKey.slice(0, 8);
    await client.query(
      `INSERT INTO "ApiKey" (id, name, "keyHash", "keyPrefix", permissions, "createdAt")
       VALUES ($1, $2, $3, $4, $5::"Permissions", NOW())
       ON CONFLICT ("keyHash") DO UPDATE SET
         name = EXCLUDED.name,
         permissions = EXCLUDED.permissions,
         "revokedAt" = NULL`,
      [id(), apiKeyName, keyHash, keyPrefix, permissions],
    );

    const adminPasswordAutoGenerated = !process.env.NOOSPHERE_ADMIN_PASSWORD;
    const apiKeyAutoGenerated = !process.env.NOOSPHERE_BOOTSTRAP_API_KEY;

    // Stage generated credentials before committing the rows that require
    // them. The final file is published only after COMMIT succeeds, so neither
    // side of the database/filesystem boundary overwrites the last recovery path.
    stagedGeneratedSecrets = stageGeneratedSecretsFile(collectGeneratedSecrets({
      adminPassword,
      adminPasswordAutoGenerated,
      adminPasswordApplied,
      apiKey: rawApiKey,
      apiKeyAutoGenerated,
    }));

    await client.query("COMMIT");
    transactionOpen = false;
    const generatedSecretsFile = publishGeneratedSecretsFile(stagedGeneratedSecrets);
    stagedGeneratedSecrets = null;

    console.log(JSON.stringify({
      ok: true,
      adminEmail,
      adminPasswordAutoGenerated,
      apiKeyAutoGenerated,
      generatedSecretsFile,
      permissions,
    }));

    if (generatedSecretsFile) {
      console.error(
        `[bootstrap] Auto-generated credentials written to ${generatedSecretsFile} with mode 0600.`,
      );
    }
  } catch (error) {
    if (transactionOpen) {
      try {
        await client.query("ROLLBACK");
      } catch (rollbackError) {
        const rollbackCode = rollbackError && typeof rollbackError === "object" &&
          "code" in rollbackError && typeof rollbackError.code === "string"
          ? ` (code=${rollbackError.code})`
          : "";
        console.error(`[bootstrap] Database rollback could not be confirmed${rollbackCode}.`);
      }
    }
    if (stagedGeneratedSecrets) {
      console.error(
        `[bootstrap] Generated credentials remain staged at ` +
          `${stagedGeneratedSecrets.pendingFile}; bootstrap did not complete.`,
      );
    }
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error(formatBootstrapError(error));
    process.exit(1);
  });
}
