import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

interface BootstrapTopic {
  name: string;
  slug: string;
  description?: string | null;
  children?: BootstrapTopic[];
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

function readBootstrapTopics() {
  return JSON.parse(
    readFileSync(resolve(repoRoot, "docker", "bootstrap-topics.json"), "utf8"),
  ) as BootstrapTopic[];
}

function readRepoFile(path: string) {
  return readFileSync(resolve(repoRoot, path), "utf8");
}

async function importBootstrapHelpers() {
  return import(pathToFileURL(resolve(repoRoot, "docker", "bootstrap.mjs")).href);
}

function makeAllowedSecretsDir(prefix: string) {
  const root = join(tmpdir(), "noosphere-bootstrap-secrets");
  mkdirSync(root, { recursive: true });
  return mkdtempSync(join(root, prefix));
}

test("bootstrap topic tree is valid and shared by seed/bootstrap scripts", () => {
  const topics = readBootstrapTopics();
  const slugs = new Set<string>();

  function visit(topic: BootstrapTopic) {
    assert.equal(typeof topic.name, "string");
    assert.equal(typeof topic.slug, "string");
    assert.match(topic.slug, /^[a-z0-9-]+$/);
    assert.equal(slugs.has(topic.slug), false, `duplicate topic slug: ${topic.slug}`);
    slugs.add(topic.slug);
    for (const child of topic.children ?? []) visit(child);
  }

  assert.ok(topics.length > 0, "bootstrap topics should not be empty");
  for (const topic of topics) visit(topic);
  assert.ok(slugs.has("noosphere"));
  assert.ok(slugs.has("pk-pro"));
  assert.ok(slugs.has("ihk-study-trainer"));
});

test("bootstrap and seed scripts load the shared topic tree file", () => {
  const bootstrapSource = readRepoFile("docker/bootstrap.mjs");
  const seedSource = readRepoFile("scripts/seed-topics.ts");

  assert.match(bootstrapSource, /bootstrap-topics\.json/);
  assert.match(seedSource, /bootstrap-topics\.json/);
  assert.doesNotMatch(bootstrapSource, /const\s+TOPICS\s*=\s*\[/);
  assert.doesNotMatch(seedSource, /const\s+TOPICS\s*=\s*\[/);
});

test("bootstrap stores generated secrets out of logs", () => {
  const bootstrapSource = readRepoFile("docker/bootstrap.mjs");
  const composeSource = readRepoFile("docker-compose.noosphere.yml");
  const installerSource = readRepoFile("install-openclaw.sh");

  assert.match(bootstrapSource, /NOOSPHERE_BOOTSTRAP_SECRETS_FILE/);
  assert.match(bootstrapSource, /writeGeneratedSecretsFile/);
  assert.doesNotMatch(bootstrapSource, /Auto-generated admin password:\s*\$\{adminPassword\}/);
  assert.doesNotMatch(bootstrapSource, /Auto-generated API key:\s*\$\{rawApiKey\}/);
  assert.match(composeSource, /NOOSPHERE_BOOTSTRAP_SECRETS_FILE/);
  assert.match(installerSource, /NOOSPHERE_BOOTSTRAP_SECRETS_FILE/);
  assert.match(installerSource, /env_get_secret "\$NOOSPHERE_HOME\/\.env" NOOSPHERE_BOOTSTRAP_SECRETS_FILE/);
});

test("bootstrap generated-secret helpers write secure JSON and preserve existing credentials", async () => {
  const { collectGeneratedSecrets, writeGeneratedSecretsFile } = await importBootstrapHelpers();
  const originalSecretsFile = process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE;
  const dir = makeAllowedSecretsDir("helper-");
  const target = join(dir, "nested", "secrets.json");

  try {
    process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE = target;

    const credentials = collectGeneratedSecrets({
      adminPassword: "admin-pass",
      adminPasswordAutoGenerated: true,
      adminPasswordApplied: true,
      apiKey: "noo_first",
      apiKeyAutoGenerated: true,
    });
    assert.deepEqual(credentials, {
      adminPassword: "admin-pass",
      apiKey: "noo_first",
    });
    assert.equal(writeGeneratedSecretsFile(credentials), target);
    assert.equal(statSync(dirname(target)).mode & 0o777, 0o700);
    assert.equal(statSync(target).mode & 0o777, 0o600);
    assert.deepEqual(JSON.parse(readFileSync(target, "utf8")).credentials, {
      adminPassword: "admin-pass",
      apiKey: "noo_first",
    });

    assert.equal(writeGeneratedSecretsFile({
      apiKey: "noo_second",
    }), target);
    assert.equal(statSync(dirname(target)).mode & 0o777, 0o700);
    assert.equal(statSync(target).mode & 0o777, 0o600);
    assert.deepEqual(JSON.parse(readFileSync(target, "utf8")).credentials, {
      adminPassword: "admin-pass",
      apiKey: "noo_second",
    });
  } finally {
    if (originalSecretsFile === undefined) {
      delete process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE;
    } else {
      process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE = originalSecretsFile;
    }
    rmSync(dir, { force: true, recursive: true });
  }
});

test("bootstrap generated-secret helpers omit unapplied and empty credentials", async () => {
  const { collectGeneratedSecrets, writeGeneratedSecretsFile } = await importBootstrapHelpers();
  const originalSecretsFile = process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE;
  const dir = makeAllowedSecretsDir("empty-");
  const target = join(dir, "secrets.json");

  try {
    process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE = target;
    const credentials = collectGeneratedSecrets({
      adminPassword: "unused-pass",
      adminPasswordAutoGenerated: true,
      adminPasswordApplied: false,
      apiKey: "unused-key",
      apiKeyAutoGenerated: false,
    });

    assert.deepEqual(credentials, {});
    assert.equal(writeGeneratedSecretsFile(credentials), null);
    assert.throws(() => statSync(target), /ENOENT/);

    writeFileSync(target, "{\"credentials\":{\"adminPassword\":\"existing\"}}\n", { mode: 0o644 });
    assert.equal(writeGeneratedSecretsFile({ apiKey: "noo_new" }), target);
    assert.equal(statSync(target).mode & 0o777, 0o600);
    assert.deepEqual(JSON.parse(readFileSync(target, "utf8")).credentials, {
      adminPassword: "existing",
      apiKey: "noo_new",
    });
  } finally {
    if (originalSecretsFile === undefined) {
      delete process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE;
    } else {
      process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE = originalSecretsFile;
    }
    rmSync(dir, { force: true, recursive: true });
  }
});

test("bootstrap generated-secret helper rejects shared parent directories", async () => {
  const { writeGeneratedSecretsFile } = await importBootstrapHelpers();
  const originalSecretsFile = process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE;

  try {
    for (const target of [
      "/tmp/noosphere-bootstrap-secrets-rejected.json",
      "/tmp/../tmp/noosphere-bootstrap-secrets-rejected.json",
      "/app/uploads/bootstrap-secrets-rejected.json",
    ]) {
      process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE = target;
      assert.throws(
        () => writeGeneratedSecretsFile({ apiKey: "noo_rejected" }),
        /must point inside a dedicated private directory/,
      );
    }
  } finally {
    if (originalSecretsFile === undefined) {
      delete process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE;
    } else {
      process.env.NOOSPHERE_BOOTSTRAP_SECRETS_FILE = originalSecretsFile;
    }
  }
});

test("bootstrap process output does not include supplied secrets or database credentials on failure", () => {
  const dir = makeAllowedSecretsDir("output-");
  const adminPassword = "sentinel-admin-password-output-test";
  const apiKey = "noo_sentinel_api_key_output_test";
  const databasePassword = "sentinel-database-password-output-test";

  try {
    const result = spawnSync(
      process.execPath,
      [resolve(repoRoot, "docker", "bootstrap.mjs")],
      {
        cwd: repoRoot,
        encoding: "utf8",
        timeout: 5_000,
        env: {
          ...process.env,
          DATABASE_URL: `postgresql://noosphere:${databasePassword}@127.0.0.1:1/noosphere`,
          NOOSPHERE_ADMIN_PASSWORD: adminPassword,
          NOOSPHERE_BOOTSTRAP_API_KEY: apiKey,
          NOOSPHERE_BOOTSTRAP_SECRETS_FILE: join(dir, "private", "secrets.json"),
        },
      },
    );

    assert.notEqual(result.status, 0);
    const output = `${result.stdout}\n${result.stderr}`;
    assert.doesNotMatch(output, new RegExp(adminPassword));
    assert.doesNotMatch(output, new RegExp(apiKey));
    assert.doesNotMatch(output, new RegExp(databasePassword));
    assert.match(output, /\[bootstrap\] Failed to initialize Noosphere \(name=Error, code=ECONNREFUSED\)\./);
  } finally {
    rmSync(dir, { force: true, recursive: true });
  }
});
